changed font family
RikitoNoto/silkroad.github.io pull request #4
Opened 2023-07-06 10:29 UTC by 10kota

Changed fonts from Avenir, Helvetica, Arial to Popins.

2023-07-06 12:34 UTC, RikitoNoto requested changes

2023-07-06 12:34 UTC, RikitoNoto commented on src/App.vue
> +  font-family: Popins, sans-serif;
使ってる環境ではフォント変わっていましたか？
私の環境だとうまく適用されないみたいで、調べたら以下の点が気になりました。
 - 「Popins」というフォントが見つからない。「Poppins」の誤字？
 - [CSSで指定できる](https://www.yuu-diaryblog.com/2016/10/09/font/)フォントの中に「Poppins」が見つからない。
  上記のサイトに書いてあるのがすべてではないと思いますが、ほかのサイトでも使われている箇所は見つからず。。。
 - Googleフォントの場合はOSにインストールされているわけではないので、[別途処理](https://peraichi.com/univ/20220502)が必要？

以上3点確認してみてください。

2023-07-06 12:34 UTC, RikitoNoto commented on src/App.vue
> -  font-family: Avenir, Helvetica, Arial, sans-serif;
変更の必要とかはないですが、なんで「sans-serif」を残して他のを消したんでしたっけ？

2023-07-08 05:44 UTC, 10kota commented
更新

2023-07-08 06:30 UTC, 10kota commented
変更の必要とかはないですが、なんで「sans-serif」を残して他のを消したんでしたっけ？ 
・"Poppins"が利用可能な場合はそれを使用し、利用できない場合はデフォルトのsans-serifフォントを使用するために追加しました。フォントの一部又は全てを変更すればいいのか分からず、このような形になりました。

使ってる環境ではフォント変わっていましたか？
私の環境だとうまく適用されないみたいで、調べたら以下の点が気になりました。

「Popins」というフォントが見つからない。「Poppins」の誤字？
CSSで指定できるフォントの中に「Poppins」が見つからない。
上記のサイトに書いてあるのがすべてではないと思いますが、ほかのサイトでも使われている箇所は見つからず。。。
Googleフォントの場合はOSにインストールされているわけではないので、別途処理が必要？
以上3点確認してみてください。

.ウェブブラウザ上で表記されているソースコードで確認した際に、Popinsと表記があったため、表示が出来ていると勘違いしました。改めて見返すとPoppinsの誤字で、表記されていなかったためsans-serifが表記されていました。
・Poppinsフォントはcssで指定できますがgoogleフォントでインストールが必要で別途処理が必要です。cssで指定できるフォントという概念がなく、自分のPCに表示されているフォントを記入しました。


・cssで指定ができるフォント尚且つ、標準搭載されているフォントに改変します。

2023-07-08 06:38 UTC, RikitoNoto commented
> cssで指定ができるフォント尚且つ、標準搭載されているフォントに改変します。

別にcssで標準搭載されているフォントを使用しなくても、[コメントで送った記事](https://peraichi.com/univ/20220502)でできそうであればpoppinsにしてもらって大丈夫ですよ。

> "Poppins"が利用可能な場合はそれを使用し、利用できない場合はデフォルトのsans-serifフォントを使用するために追加しました。フォントの一部又は全てを変更すればいいのか分からず、このような形になりました。

利用できない場合って、どんな時でしょう？
もしそういうタイミングが存在するのであれば、今消しちゃったけど追加したほうがいいのではないかな？

2023-07-08 07:26 UTC, 10kota commented
> 別にcssで標準搭載されているフォントを使用しなくても、[コメントで送った記事](https://peraichi.com/univ/20220502)でできそうであればpoppinsにしてもらって大丈夫ですよ。
> 
 検討した上でもう一度提出します。
> 
> 利用できない場合って、どんな時でしょう？ もしそういうタイミングが存在するのであれば、今消しちゃったけど追加したほうがいいのではないかな？

ウェブサイトを閲覧するユーザーのデバイスやブラウザには異なるフォントがインストールされているため、指定したフォントを表示できない可能性があります。
又、コードは一番下の欄が優先されるという先入観があり、sans-serifが表記されると勘違いしたため今あるプルリクエストはmonospaceとなっています。

2023-07-15 15:01 UTC, closed without merging